### PR TITLE
corci ci: Move repo from gerrit

### PR DESCRIPTION
**Pull request by JohnMalmberg**
Move the provisioning script repository from Gerrit.

Signed-off-by: John.E.Malmberg <john.e.malmberg@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
I should ask, is there any reason to not use a github private repo for the referenced project?

**Comment by JohnMalmberg** [comment]
> I should ask, is there any reason to not use a github private repo for the referenced project?

I do not want these scripts which only work with our internal configuration exposed outside of the company at this time, even in a github private repo.

**Comment by jolivier23** [comment]
Is there a ticket for this?

**Comment by JohnMalmberg** [comment]
CORCI-684 is the ticket.

**Pull request merged**
