### PR TITLE
DAOS-16147 test: Prevent running unintentional HW stages

### PR DESCRIPTION
**Pull request by phender**
When builds originally started by a github push are restarted retain the original skip logic from the push when determining which stages top run.

### CODE REVIEW

**Comment by phender** [comment]
Unit tests passed w/ self-reference in https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-442/7

**Comment by phender** [comment]
Tested via https://github.com/daos-stack/daos/pull/14699 / https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14699:
- None of the restarted builds ran with more than the normal amount of VM stages.

**Review by daltonbohning — APPROVED** [review]

**Review by JohnMalmberg — APPROVED** [review]

**Comment by phender** [comment]
In https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fpipeline-lib/detail/PR-442/9/pipeline the downstream testing in the master branch originally failed to checkout out code from github (unrelated to this PR) in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pipeline-lib-PR-442-master/10/pipeline/.  A manual re-run of this stage in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pipeline-lib-PR-442-master/13/pipeline/ passed.

**Review by brianjmurrell — APPROVED** [review]

**Comment by phender** [comment]
To test if this PR fixes the behavior, https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14699/9/pipeline/780/ was run with the `test_always_fails_hw` test.  It was then re-run in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14699/10/pipeline/ and did not include any additional stages.

**Pull request merged**
