### PR TITLE
SRE-2077 ci: Add git remote prune to checkout.

### PR DESCRIPTION
**Pull request by phender**
Implementing a git remote prune as part of the git checkout
process as defined in https://github.com/jenkinsci/git-plugin

### CODE REVIEW

**Review by JohnMalmberg — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]
Seems reasonable.  Is there some documentation you can refer a reader to about this option that we can include in the commit message?

I can see it exists in the source of https://www.jenkins.io/doc/pipeline/steps/workflow-scm-step/ but not seeing on the display version of that page.

**Comment by phender** [comment]
Its working now https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pipeline-lib-PR-422-weekly-testing/4/pipeline/76/

**Review by daltonbohning — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]
It doesn't seem to be breaking anything at least.  Do we know it's working though?

I was kind of expecting to see something about pruning in the [example run](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pipeline-lib-PR-422-weekly-testing/4/pipeline/79)'s _Check out from version control_ step.

I guess we can land it and find out.  Or is there some additional testing that you can/want to do @phender to verify it's achieving the goal?

**Comment by phender** [comment]
> It doesn't seem to be breaking anything at least. Do we know it's working though?
> 
> I was kind of expecting to see something about pruning in the [example run](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pipeline-lib-PR-422-weekly-testing/4/pipeline/79)'s _Check out from version control_ step.
> 
> I guess we can land it and find out. Or is there some additional testing that you can/want to do @phender to verify it's achieving the goal?

I referenced this PR in a quick `daily-testing` PR and I see the `--prune` option added to the `git fetch` here:
```
[2024-02-28T20:42:48.864Z] [Functional Hardware Medium] Check out 'master' from version control
[2024-02-28T20:42:49.151Z] The recommended git tool is: git
[2024-02-28T20:42:49.162Z] No credentials specified
[2024-02-28T20:42:49.183Z] Fetching changes from the remote Git repository
[2024-02-28T20:42:49.192Z] Pruning obsolete local branches
[2024-02-28T20:42:49.830Z] Checking out Revision de031fdccfd588d86e14cc46d48ba4b3482aa787 (origin/master)
[2024-02-28T20:42:49.165Z]  > git rev-parse --resolve-git-dir /var/lib/jenkins/jenkins-1/ci_node_wolf-137-141/workspace/daos-stack_daos_PR-13895/.git # timeout=10
[2024-02-28T20:42:49.187Z]  > git config remote.origin.url https://github.com/daos-stack/daos.git # timeout=10
[2024-02-28T20:42:49.193Z] Fetching upstream changes from https://github.com/daos-stack/daos.git
[2024-02-28T20:42:49.193Z]  > git --version # timeout=10
[2024-02-28T20:42:49.198Z]  > git --version # 'git version 2.40.1'
[2024-02-28T20:42:49.198Z]  > git fetch --no-tags --force --progress --prune -- https://github.com/daos-stack/daos.git +refs/heads/*:refs/remotes/origin/* # timeout=10
[2024-02-28T20:42:49.822Z]  > git rev-parse origin/master^{commit} # timeout=10
[2024-02-28T20:42:49.831Z]  > git config core.sparsecheckout # timeout=10
[2024-02-28T20:42:49.833Z]  > git checkout -f de031fdccfd588d86e14cc46d48ba4b3482aa787 # timeout=10
[2024-02-28T20:42:50.299Z] Commit message: "DAOS-15235 test: tag tests with class name (#13826)"
[2024-02-28T20:42:50.299Z] First time build. Skipping changelog.
[2024-02-28T20:42:50.302Z]  > git remote # timeout=10
[2024-02-28T20:42:50.305Z]  > git submodule init # timeout=10
[2024-02-28T20:42:50.333Z]  > git submodule sync # timeout=10
[2024-02-28T20:42:50.361Z]  > git config --get remote.origin.url # timeout=10
[2024-02-28T20:42:50.366Z]  > git submodule init # timeout=10
[2024-02-28T20:42:50.394Z]  > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
[2024-02-28T20:42:50.396Z]  > git config --get submodule.raft.url # timeout=10
[2024-02-28T20:42:50.398Z]  > git remote # timeout=10
[2024-02-28T20:42:50.400Z]  > git config --get remote.origin.url # timeout=10
[2024-02-28T20:42:50.403Z]  > git config -f .gitmodules --get submodule.raft.path # timeout=10
[2024-02-28T20:42:50.405Z]  > git submodule update --init --recursive src/rdb/raft # timeout=10
```

**Comment by brianjmurrell** [comment]
> I referenced this PR in a quick `daily-testing` PR and I see the `--prune` option added to the `git fetch` here:

Interesting that it wasn't in the downstream testing.  That downstream testing is supposed to use the pipeline-lib PR.

**Comment by phender** [comment]
> > I referenced this PR in a quick `daily-testing` PR and I see the `--prune` option added to the `git fetch` here:
> 
> Interesting that it wasn't in the downstream testing. That downstream testing is supposed to use the pipeline-lib PR.

I don't have an explanation.  Before 4th commit, the downstream testing was failing to run the git checkout with obviously the code in the PR.

**Comment by phender** [comment]
The only issue encountered in testing was fault injection warnings in the master branch downstream testing: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pipeline-lib-PR-422-master/7/Fault_Injection/

**Pull request merged**
