### PR TITLE
CORCI-1032 nlt: Do not ignore LOW severity regressions.

### PR DESCRIPTION
**Pull request by ashleypittman**
This was allowed due to race conditions in the code but they're fixed
so remove the provision for this.

Tidy up some legacy code that's not required any more.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
https://github.com/daos-stack/daos/pull/4160 needs to land after this.

**Review by brianjmurrell — DISMISSED** [review]

**Review by brianjmurrell — COMMENTED** [review]
What is going to happen to DAOS PRs in flight that are expecting the old behaviour (i.e. that are still requesting `unitTestPost` with `record_issues: false`)?

**Comment by ashleypittman** [comment]
> What is going to happen to DAOS PRs in flight that are expecting the old behaviour (i.e. that are still requesting `unitTestPost` with `record_issues: false`)?

I think it's OK, as they're providing the default value.  The only concern I had was if they passed a now known parameter, but I don't know how that's checked in Groovy.  The whole record_issues thing was only for backwards compatibility when I split NLT out from unit test so it's all legacy now, it's just a question of how we unwind it.

**Comment by brianjmurrell** [comment]
> I think it's OK, as they're providing the default value. The only concern I had was if they passed a now known parameter, but I don't know how that's checked in Groovy. The whole record_issues thing was only for backwards compatibility when I split NLT out from unit test so it's all legacy now, it's just a question of how we unwind it.

Oh yes.  I was losing sight of the removal of `!stage_info['with_valgrind'] && record_issues) ||` from the `if`.

Unused (i.e. unknown) values in `config` are fine.  It's just a `Map` (hash or associative array, in other languages) which values are pulled from in the Groovy function.  We could just very well pass positional parameters instead of a Map.  A Map is just really easy to work with, adding and removing function _parameters_ without having to worry about compatibility of function signatures, etc.  Frankly though, we have probably over-used it, and could use some real positional parameters to functions in some places.

**Review by brianjmurrell — APPROVED** [review]

**Review by phender — APPROVED** [review]

**Pull request merged**
