### PR TITLE
DAOS-15859 test: Adding support for release/2.6

### PR DESCRIPTION
**Pull request by phender**
Testing release/2.6 with EL 8.8 and Leap 15.5.

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]

**Comment by phender** [comment]
Obviously, this can't land with https://github.com/daos-stack/pipeline-lib/blob/c048286676dae609eb83bfa3976f9e1d3f541ea7/Jenkinsfile#L21.  So, another push will be needed after confirming the changes pass tests.

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
LGTM.  I will change my -1 to +1 once the `@Library` is removed (just to prevent somebody accidentally/prematurely landing this seeing a +1 on it).

**Comment by phender** [comment]
The https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pipeline-lib-PR-438-release-2.6/1 build failed with an issue reported on master:
```
[2024-05-21T16:35:06.574Z] Error: 
[2024-05-21T16:35:06.574Z]  Problem 1: conflicting requests
[2024-05-21T16:35:06.574Z]   - nothing provides /usr/libexec/platform-python needed by python3-dnf-4.7.0-16.el8_8.noarch from daos_ci-rocky8-base-artifactory
[2024-05-21T16:35:06.574Z]  Problem 2: package python3-dnf-plugins-core-4.0.21-19.el8_8.noarch from daos_ci-rocky8-base-artifactory requires python3-dnf >= 4.7.0-6, but none of the providers can be installed
[2024-05-21T16:35:06.574Z]   - conflicting requests
[2024-05-21T16:35:06.574Z]   - nothing provides /usr/libexec/platform-python needed by python3-dnf-4.7.0-16.el8_8.noarch from daos_ci-rocky8-base-artifactory
```
The proposed solution is to move fedora containers back from 40 to 37 until the compatibility can be resolved.

**Comment by phender** [comment]
All tests passed in https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-438/4/

**Comment by phender** [comment]
As expected, https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-438/5/ failed just the `distroVersion() tests`.

**Review by daltonbohning — APPROVED** [review]

**Review by JohnMalmberg — APPROVED** [review]

**Pull request merged**
