### PR TITLE
CORCI-1011 unit-test: Abort the build on test failure/unstable result

### PR DESCRIPTION
**Pull request by ashleypittman**
Change runTest() to propagate errors so that they stop the build from
advancing onto the next stage.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Since we seem to have gotten this wrong the last time, is it worth pushing a couple of DAOS PRs instrumented to test the changes?

**Comment by ashleypittman** [comment]
> Since we seem to have gotten this wrong the last time, is it worth pushing a couple of DAOS PRs instrumented to test the changes?

Earlier versions of https://github.com/daos-stack/daos/pull/3849 did just that and works in the cases I tested, but then I realised that the timeout issue was more important so updated it to just include them.

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by ashleypittman** [comment]
I had a thought about this, for master we possibly do want to run subsequent tests.

**Review by brianjmurrell — APPROVED** [review]
LGTM.  @JohnMalmberg Any issues with this one?

**Review by JohnMalmberg — APPROVED** [review]

**Comment by jolivier23** [comment]
what is the failure about?

**Comment by ashleypittman** [comment]
> what is the failure about?

@JohnMalmberg would know, but it's unrelated and is happening on other pipeline-lib PRs.  I've asked him to file a PR.

**Comment by JohnMalmberg** [comment]
A Nexus upgrade broke a groovy script on the Nexus server that the failing tests depended on.
We should probably just comment out the failed tests in the Jenkinsfile in the next PR that gets submitted for pipeline-lib.

**Pull request merged**
