### PR TITLE
Add initial support for Fedora

### PR DESCRIPTION
**Pull request by brianjmurrell**
Mainly just as a Vagrant host for now.

### CODE REVIEW

**Comment by ashleypittman** [comment]
What is Vagrant?

**Comment by brianjmurrell** [comment]
> What is Vagrant?

https://www.vagrantup.com/

**Comment by ashleypittman** [comment]
> > What is Vagrant?
> 
> https://www.vagrantup.com/
> 
> It's a virtual machine [cluster] orchestrator.

Ah, makes sense.  I've used virsh but that was a few years ago now.

Is there a ticket for this work?

**Comment by brianjmurrell** [comment]
> Ah, makes sense. I've used virsh but that was a few years ago now.

`virsh` is just the user-facing CLI tool for libvirt.  Vagrant is just an abstraction layer on top of libvirt (and other providers, like VirtualBox, etc.) that allows one to easily write portable (multiple) virtual machine orchestration -- to the extent that the providers have similar capabilities of course.

> Is there a ticket for this work?

https://jira.hpdd.intel.com/browse/DAOS-7214

I have a PR that provides a `Vagrantfile` to create a 3 node cluster of EL7 nodes complete with virtual NVMe and virtual PMEM. 
 The PR also has the framework to test that `Vagrantfile` on a single hardware node and run our Avocado tests in the cluster created on it, with PMEM and NVMe -- no _tmpfs_.  The tests it runs at the moment are just a few to prove that the `Vagrantfile` actually works.  There's some future work to be done to be able to more completely use such VMs with their virtual PMEM and NVMe drives.

**Review by JohnMalmberg — APPROVED** [review]

**Pull request merged**
