### PR TITLE
CORCI-1063 Build: Docker distro and DAOS repos

### PR DESCRIPTION
**Pull request by JohnMalmberg**
The Docker distros are now only for externally maintained signed
packages

The DAOS repos are for any locally build artifacts and will probably not be
officially signed.

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

### CODE REVIEW

**Review by brianjmurrell — COMMENTED** [review]
dockerBuildArgs() feels like it's getting complicated enough, with enough changes happening now and in the future that it needs some testing added to it, to make sure that these and future changes don't cause regressions for exiting/previous behaviour.  I fear us unintentionally breaking backward compatibility.

**Comment by JohnMalmberg** [comment]
Agree that adding a unit test would be a good thing.   Right now though I have run both a regression PR and a PR to validate the changes.

I would like the get the unit tests done at a later time.

**Comment by brianjmurrell** [comment]
> https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-5186/ tested this PR with yesterday's master.
> 
> https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-5363/ tested the new repositories with yesterday's master.

Would these runs needed to have rebuilt the docker images from the Dockerfiles (rather than using caches) to test the code being changed?  A brief look doesn't seem to show any docker images actually being rebuilt.  Alternatively, looking at the `docker build` commands from each run, for EL7, say, should they be different, demonstrating backward compatible behaviour and use of the new repos?  They looks the same to me (where it counts):

```
[2021-04-06T20:46:54.522Z] + docker build -t 9529422691dacc515387f8a72300023737593182 --build-arg NOBUILD=1 --build-arg UID=1101 --build-arg JENKINS_URL=https://build.hpdd.intel.com/ --build-arg CACHEBUST=1617741953075 --build-arg CB0=15 --build-arg REPO_URL=https://repo.dc.hpdd.intel.com/ --build-arg REPO_EL7=repository/daos-stack-el-7-x86_64-stable-local --build-arg REPO_DISTRO=repository/daos-stack-external-el-7-x86_64-stable-group --build-arg DAOS_DEPS_BUILD=no -f utils/rpms/packaging/Dockerfile.mockbuild utils/rpms/packaging
[2021-04-07T20:19:33.423Z] + docker build -t ee37682be4dc65308228c489c1ba9e74b7a35239 --build-arg NOBUILD=1 --build-arg UID=1101 --build-arg JENKINS_URL=https://build.hpdd.intel.com/ --build-arg CACHEBUST=1617826710331 --build-arg CB0=15 --build-arg REPO_URL=https://repo.dc.hpdd.intel.com/ --build-arg REPO_EL7=repository/daos-stack-el-7-x86_64-stable-local --build-arg REPO_DISTRO=repository/daos-stack-external-el-7-x86_64-stable-group --build-arg DAOS_DEPS_BUILD=no -f utils/rpms/packaging/Dockerfile.mockbuild utils/rpms/packaging
```

**Comment by JohnMalmberg** [comment]
Changing the current master to cachebust the dockerfiles using our hard coded reponames is likely not to pass based on what I had to do to get the new dockerfiles to work.   The current EPEL public GPG key is not in the base dockerfile, but is apparently in the cached layers that currently allow it to work.

The dockerfiles for RPM building and checkpatch should still be using the old methods.  You should not see a change.
I see that the older Jenkinsfile docker builds are getting an additional REPO_DISTRO --build-arg that they are ignoring.

Since they are ignoring that parameter, I do not think it is worth figuring out how to suppress it.

We are currently proxying the Fedora repositories, so in the future we can look at adding environment variables for a group repository for them.

Where you will see a difference is in the non-RPM builds of CentOS and Leap.
`
15:19:43  + docker build -t 9e953a410ca76c501689bc68ea75f0aae9e0b7fd --build-arg NOBUILD=1 --build-arg UID=1101 --build-arg JENKINS_URL=https://build.hpdd.intel.com/ --build-arg CACHEBUST=1617826710331 --build-arg CB0=15 --build-arg REPO_URL=https://repo.dc.hpdd.intel.com/ --build-arg REPO_DAOS=repository/daos-stack-centos-7-x86_64-stable-group --build-arg REPO_DISTRO=repository/daos-stack-docker-centos-7-x86_64-stable-group --build-arg DAOS_DEPS_BUILD=no -t daos-stack-daos-pr-5363-centos7 --build-arg QUICKBUILD_DEPS= --build-arg 'REPOS= ' -f utils/docker/Dockerfile.centos.7 .
`

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
