### PR TITLE
DAOS-7284: add centos7  clang  debug

### PR DESCRIPTION
**Pull request by daltonbohning**
Add stage "Build on CentOS 7 with Clang debug"

Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>

### CODE REVIEW

**Comment by daltonbohning** [comment]
Needed for https://github.com/daos-stack/daos/pull/5542

**Review by ashleypittman — APPROVED** [review]
Seems to work but is a bit odd.

**Comment by ashleypittman** [comment]
@brianjmurrell can you take a look at this please?

**Comment by brianjmurrell** [comment]
> Seems to work but is a bit odd.

What's odd?

**Review by brianjmurrell — APPROVED** [review]

**Comment by ashleypittman** [comment]
> > Seems to work but is a bit odd.
> 
> What's odd?

That you need to modify pipeline-lib purely to add a new build stage.

**Pull request merged**
