### PR TITLE
DAOS-5342 test: add new results.xml path file to report big files

### PR DESCRIPTION
**Pull request by amjustin13**
Add log_size_check.xml file to results to be reported.

Signed-off-by: Justiniano-pagn <amanda.justiniano-pagn@intel.com>

### CODE REVIEW

**Review by phender — APPROVED** [review]
This is working as intended in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-2029/42/ and collects errors such as https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-2029/42/testReport/junit/(root)/cart-cart_iv_two_node/Test___Functional_on_CentOS_7___ALL/

**Comment by phender** [comment]
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3625/1/ was run to verify this change had no adverse effects on a normal CI run and all tests passed.

**Comment by brianjmurrell** [comment]
What about our discussion of making this file more generic?  Any further thoughts there before we commit something we will just only end up making more generic at some point?  Worth considering and taking care of that now?

**Comment by phender** [comment]
> What about our discussion of making this file more generic? Any further thoughts there before we commit something we will just only end up making more generic at some point? Worth considering and taking care of that now?

I don't think we have that fully designed at this point, i.e. will there be one JUnit file for all post-run activities or separate ones.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
